apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: database
  labels:
    app: mysql
    tier: database

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: database

  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
        - name: database-container
          image: 061186295720.dkr.ecr.us-east-1.amazonaws.com/docker-containers-database-repo:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: secret-registry
